name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 22f1001679@ds.study.iitm.ac.in
        run: echo "Hello, world!"
